name: Daily Backup

on:
  schedule:
    - cron: '0 2 * * *'  # 2 AM daily
  workflow_dispatch:  # Manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create backup
        run: |
          DATE=$(date +%Y%m%d)
          mkdir -p backup/$DATE
          cp -r src/* backup/$DATE/
          
      - name: Commit backup
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add backup/
          git commit -m "Automated backup $(date +%Y-%m-%d)"
          git push
